[book]
authors = ["Bigghis"]
language = "it"
multilingual = false
src = "src"
title = "AI appunti"

[output.html]
default-theme = "ayu"
git-repository-url = ""

[output.html.fold]
enable = false
level = 1

[output.html.playground]
editable = false

[output.html.print]
enable = false
